---
features:
  - |
    Add :class:`~qiskit_experiments.framework.ExperimentConfig` dataclass
    for storing the configuration of an experiment. This configuration can
    be obtained by using the
    :meth:`~qiskit_experiments.framework.BaseExperiment.config` property.
    Experiments can also be reconstructed from their configuration using
    the :meth:`~qiskit_experiments.framework.BaseExperiment.from_config`
    class method.
